export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';   
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';  
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';
export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const TERMINATE_NOTIFICATION = 'TERMINATE_NOTIFICATION';