export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';   
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';  
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';
export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const TERMINATE_NOTIFICATION = 'TERMINATE_NOTIFICATION';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCTS_IN_STORE = 'UPDATE_PRODUCTS_IN_STORE';
export const UPDATE_PRODUCT_IN_STORE = 'UPDATE_PRODUCT_IN_STORE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_FIELD = 'EDIT_FIELD';
